import { Customer, Order, Deal } from './types';

export const initialCustomers: Customer[] = [
  {
    id: 'cust1',
    name: 'Иванов Алексей Петрович',
    phone: '+7 (999) 123-45-67',
    email: 'ivanov@mail.ru',
    address: 'г. Москва, ул. Садовая, д. 15, кв. 42',
    type: 'individual',
    source: 'Instagram',
    notes: 'Постоянный клиент, предпочитает хвойные. Участок 10 соток.',
    createdAt: '2024-03-15',
    totalOrders: 5,
    totalSpent: 85000,
  },
  {
    id: 'cust2',
    name: 'ООО "Зелёный Дом"',
    phone: '+7 (495) 555-33-22',
    email: 'info@zelenydom.ru',
    address: 'г. Москва, Ленинградский пр-т, д. 80',
    type: 'business',
    source: 'Сайт',
    notes: 'Ландшафтная компания. Оптовые заказы от 50 000 руб.',
    createdAt: '2024-01-20',
    totalOrders: 12,
    totalSpent: 450000,
  },
  {
    id: 'cust3',
    name: 'Петрова Мария Сергеевна',
    phone: '+7 (916) 777-88-99',
    email: 'petrova.m@gmail.com',
    address: 'МО, г. Одинцово, КП "Лесная поляна"',
    type: 'designer',
    source: 'Рекомендация',
    notes: 'Ландшафтный дизайнер. Приводит клиентов, скидка 15%.',
    createdAt: '2024-02-10',
    totalOrders: 8,
    totalSpent: 320000,
  },
  {
    id: 'cust4',
    name: 'Сидоров Дмитрий Иванович',
    phone: '+7 (926) 444-55-66',
    email: 'sidorov.d@yandex.ru',
    address: 'г. Москва, ул. Ленина, д. 25',
    type: 'individual',
    source: 'Авито',
    notes: 'Новый клиент, интересуется ягодными культурами.',
    createdAt: '2024-11-01',
    totalOrders: 1,
    totalSpent: 12000,
  },
  {
    id: 'cust5',
    name: 'ЖК "Сосновый бор"',
    phone: '+7 (495) 111-22-33',
    email: 'ozelenenie@sosnovybor.ru',
    address: 'МО, г. Химки, мкр. Сходня',
    type: 'developer',
    source: 'Тендер',
    notes: 'Застройщик. Крупный заказ на озеленение территории ЖК.',
    createdAt: '2024-09-15',
    totalOrders: 2,
    totalSpent: 1200000,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord1',
    customerId: 'cust1',
    customerName: 'Иванов Алексей Петрович',
    items: [
      { plantId: '1', plantName: 'Туя западная Смарагд', quantity: 10, price: 800 },
      { plantId: '3', plantName: 'Можжевельник казацкий', quantity: 5, price: 600 },
    ],
    totalAmount: 11000,
    status: 'delivered',
    paymentStatus: 'paid',
    createdAt: '2024-11-15',
    deliveryDate: '2024-11-18',
    notes: 'Доставка до подъезда. Клиент просил позвонить за час.',
  },
  {
    id: 'ord2',
    customerId: 'cust2',
    customerName: 'ООО "Зелёный Дом"',
    items: [
      { plantId: '2', plantName: 'Гортензия метельчатая', quantity: 20, price: 700 },
      { plantId: '4', plantName: 'Спирея японская', quantity: 50, price: 350 },
    ],
    totalAmount: 31500,
    status: 'ready',
    paymentStatus: 'paid',
    createdAt: '2024-12-10',
    deliveryDate: '2024-12-20',
    notes: 'Оптовый заказ. Скидка 15% для партнёра.',
  },
  {
    id: 'ord3',
    customerId: 'cust3',
    customerName: 'Петрова Мария Сергеевна',
    items: [
      { plantId: '5', plantName: 'Ель коника', quantity: 3, price: 1500 },
      { plantId: '6', plantName: 'Сосна горная Мугус', quantity: 5, price: 900 },
    ],
    totalAmount: 9000,
    status: 'processing',
    paymentStatus: 'partial',
    createdAt: '2024-12-18',
    deliveryDate: '2024-12-25',
    notes: 'Предоплата 50%. Остаток при получении.',
  },
  {
    id: 'ord4',
    customerId: 'cust4',
    customerName: 'Сидоров Дмитрий Иванович',
    items: [
      { plantId: '7', plantName: 'Голубика высокорослая', quantity: 6, price: 800 },
      { plantId: '8', plantName: 'Жимолость съедобная', quantity: 4, price: 400 },
    ],
    totalAmount: 6400,
    status: 'new',
    paymentStatus: 'pending',
    createdAt: '2024-12-22',
    deliveryDate: '2024-12-28',
    notes: 'Первый заказ. Нужна консультация по посадке.',
  },
  {
    id: 'ord5',
    customerId: 'cust5',
    customerName: 'ЖК "Сосновый бор"',
    items: [
      { plantId: '9', plantName: 'Туя западная Смарагд', quantity: 200, price: 650 },
      { plantId: '10', plantName: 'Спирея японская', quantity: 500, price: 280 },
    ],
    totalAmount: 270000,
    status: 'processing',
    paymentStatus: 'partial',
    createdAt: '2024-12-01',
    deliveryDate: '2025-03-15',
    notes: 'Крупный заказ на озеленение. Предоплата 30%. Остаток по факту доставки партиями.',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal1',
    title: 'Озеленение коттеджного посёлка',
    customerName: 'Иванов Алексей Петрович',
    value: 250000,
    stage: 'proposal',
    probability: 60,
    expectedCloseDate: '2025-02-15',
    createdAt: '2024-12-10',
    notes: 'Клиент заинтересован в комплексном озеленении участка. Нужен проект.',
  },
  {
    id: 'deal2',
    title: 'Поставка растений для ЖК',
    customerName: 'ЖК "Сосновый бор"',
    value: 800000,
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: '2025-01-30',
    createdAt: '2024-11-20',
    notes: 'Второй этап озеленения. Обсуждаем условия оплаты и сроки.',
  },
  {
    id: 'deal3',
    title: 'Дизайн-проект сада',
    customerName: 'Петрова Мария Сергеевна',
    value: 150000,
    stage: 'qualified',
    probability: 40,
    expectedCloseDate: '2025-03-01',
    createdAt: '2024-12-15',
    notes: 'Новый клиент от дизайнера. Нужна встреча и осмотр участка.',
  },
  {
    id: 'deal4',
    title: 'Оптовая поставка туи',
    customerName: 'ООО "Зелёный Дом"',
    value: 180000,
    stage: 'won',
    probability: 100,
    expectedCloseDate: '2024-12-20',
    createdAt: '2024-11-25',
    notes: 'Сделка закрыта. Договор подписан. Ожидается оплата.',
  },
  {
    id: 'deal5',
    title: 'Ягодный сад под ключ',
    customerName: 'Сидоров Дмитрий Иванович',
    value: 85000,
    stage: 'lead',
    probability: 20,
    expectedCloseDate: '2025-04-01',
    createdAt: '2024-12-22',
    notes: 'Клиент интересуется созданием ягодного сада. Нужна консультация.',
  },
];
