import { Plant, Zone, Task, PlantType } from './types';

export const PLANT_TYPE_LABELS: Record<PlantType, string> = {
  pine: 'Сосна',
  spruce: 'Ель',
  fir: 'Пихта',
  juniper: 'Можжевельник',
  cypress: 'Кипарисовик',
  thuja: 'Туя',
  yew: 'Тис',
  larch: 'Лиственница',
};

export const PLANT_TYPE_EMOJIS: Record<PlantType, string> = {
  pine: '🌲',
  spruce: '🎄',
  fir: '🌲',
  juniper: '🌿',
  cypress: '🌳',
  thuja: '🌲',
  yew: '🌿',
  larch: '🍃',
};

export const HEALTH_LABELS = {
  excellent: 'Отличное',
  good: 'Хорошее',
  fair: 'Удовлетворительное',
  poor: 'Плохое',
  critical: 'Критическое',
};

export const HEALTH_COLORS = {
  excellent: '#22c55e',
  good: '#84cc16',
  fair: '#eab308',
  poor: '#f97316',
  critical: '#ef4444',
};

export const STATUS_LABELS = {
  growing: 'Растёт',
  transplanting: 'Пересадка',
  resting: 'Покой',
  sold: 'Продано',
  planned: 'Запланировано',
};

export const STATUS_COLORS = {
  growing: '#22c55e',
  transplanting: '#3b82f6',
  resting: '#a855f7',
  sold: '#6b7280',
  planned: '#f59e0b',
};

export const initialPlants: Plant[] = [
  // Хвойные
  {
    id: '1',
    name: 'Сосна горная Мугус',
    latinName: 'Pinus mugo Mughus',
    type: 'pine',
    variety: 'Mughus',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2022-03-15',
    height: 85,
    age: 4,
    notes: 'Хорошо перенесла зиму. Нужна формирующая обрезка весной.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-11-01',
    financials: { costPerUnit: 200, sellingPrice: 900, profitPerUnit: 700, roi: 350, paybackMonths: 9, demand: 'high' },
  },
  {
    id: '2',
    name: 'Ель голубая',
    latinName: 'Picea pungens',
    type: 'spruce',
    variety: 'Hoopsii',
    health: 'good',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2021-05-20',
    height: 145,
    age: 6,
    notes: 'Активный рост. Требуется подкормка.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-10-15',
    financials: { costPerUnit: 250, sellingPrice: 1200, profitPerUnit: 950, roi: 380, paybackMonths: 8, demand: 'high' },
  },
  {
    id: '3',
    name: 'Можжевельник казацкий',
    latinName: 'Juniperus sabina',
    type: 'juniper',
    variety: 'Tamariscifolia',
    health: 'good',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2023-04-10',
    height: 35,
    age: 2,
    notes: 'Молодое растение. Хорошо укоренилось.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-11-20',
    financials: { costPerUnit: 100, sellingPrice: 600, profitPerUnit: 500, roi: 500, paybackMonths: 6, demand: 'very-high' },
  },
  {
    id: '4',
    name: 'Туя западная Смарагд',
    latinName: 'Thuja occidentalis',
    type: 'thuja',
    variety: 'Smaragd',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона В',
    plantedDate: '2023-06-01',
    height: 60,
    age: 3,
    notes: 'Отлично растёт. Готов к продаже через год.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-11-15',
    financials: { costPerUnit: 150, sellingPrice: 800, profitPerUnit: 650, roi: 433, paybackMonths: 8, demand: 'very-high' },
  },
  {
    id: '5',
    name: 'Пихта корейская',
    latinName: 'Abies koreana',
    type: 'fir',
    variety: 'Blue Standard',
    health: 'good',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2022-09-10',
    height: 95,
    age: 4,
    notes: 'Медленный рост, но очень декоративная.',
    lastWatered: '2024-12-17',
    lastFertilized: '2024-10-20',
    financials: { costPerUnit: 300, sellingPrice: 1500, profitPerUnit: 1200, roi: 400, paybackMonths: 7, demand: 'high' },
  },
  {
    id: '6',
    name: 'Кипарисовик горохоплодный',
    latinName: 'Chamaecyparis pisifera',
    type: 'cypress',
    variety: 'Filifera Aurea',
    health: 'good',
    status: 'growing',
    zone: 'Зона В',
    plantedDate: '2023-05-15',
    height: 45,
    age: 2,
    notes: 'Яркая золотистая хвоя. Требует защиты от весеннего солнца.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-11-10',
    financials: { costPerUnit: 180, sellingPrice: 850, profitPerUnit: 670, roi: 372, paybackMonths: 8, demand: 'medium' },
  },
  {
    id: '7',
    name: 'Тис ягодный',
    latinName: 'Taxus baccata',
    type: 'yew',
    variety: 'Fastigiata',
    health: 'good',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2022-11-20',
    height: 70,
    age: 5,
    notes: 'Колонновидная форма. Отлично подходит для живых изгородей.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-10-25',
    financials: { costPerUnit: 220, sellingPrice: 1100, profitPerUnit: 880, roi: 400, paybackMonths: 7, demand: 'high' },
  },
  {
    id: '8',
    name: 'Лиственница японская',
    latinName: 'Larix kaempferi',
    type: 'larch',
    variety: 'Diana',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2021-04-05',
    height: 180,
    age: 6,
    notes: 'Быстрый рост. Осенью красивая золотая хвоя.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-11-05',
    financials: { costPerUnit: 280, sellingPrice: 1300, profitPerUnit: 1020, roi: 364, paybackMonths: 8, demand: 'medium' },
  },
  // Ягодные
  {
    id: '9',
    name: 'Голубика высокорослая',
    latinName: 'Vaccinium corymbosum',
    type: 'juniper',
    variety: 'Патриот',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона Г',
    plantedDate: '2023-04-20',
    height: 50,
    age: 2,
    notes: 'Суперфуд с огромным спросом. Ягоды 500-1500 руб/кг.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-11-25',
    financials: { costPerUnit: 200, sellingPrice: 800, profitPerUnit: 600, roi: 300, paybackMonths: 12, demand: 'very-high' },
  },
  {
    id: '10',
    name: 'Жимолость съедобная',
    latinName: 'Lonicera caerulea',
    type: 'juniper',
    variety: 'Бакчарская',
    health: 'good',
    status: 'growing',
    zone: 'Зона Г',
    plantedDate: '2023-05-10',
    height: 40,
    age: 2,
    notes: 'Самая ранняя ягода! Созревает в июне.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-11-20',
    financials: { costPerUnit: 100, sellingPrice: 400, profitPerUnit: 300, roi: 300, paybackMonths: 8, demand: 'high' },
  },
  // Декоративные
  {
    id: '11',
    name: 'Гортензия метельчатая',
    latinName: 'Hydrangea paniculata',
    type: 'juniper',
    variety: 'Лаймлайт',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона В',
    plantedDate: '2023-06-15',
    height: 55,
    age: 2,
    notes: 'Тренд последних лет! Огромные соцветия.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-11-30',
    financials: { costPerUnit: 150, sellingPrice: 700, profitPerUnit: 550, roi: 367, paybackMonths: 8, demand: 'very-high' },
  },
  {
    id: '12',
    name: 'Спирея японская',
    latinName: 'Spiraea japonica',
    type: 'juniper',
    variety: 'Голден Принцесс',
    health: 'good',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2023-07-01',
    height: 30,
    age: 1,
    notes: 'Неприхотливый кустарник с яркой листвой.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-11-15',
    financials: { costPerUnit: 80, sellingPrice: 350, profitPerUnit: 270, roi: 338, paybackMonths: 6, demand: 'high' },
  },
  {
    id: '13',
    name: 'Лаванда узколистная',
    latinName: 'Lavandula angustifolia',
    type: 'juniper',
    variety: 'Hidcote',
    health: 'good',
    status: 'growing',
    zone: 'Зона В',
    plantedDate: '2023-08-20',
    height: 25,
    age: 1,
    notes: 'Трендовое ароматное растение.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-11-10',
    financials: { costPerUnit: 80, sellingPrice: 350, profitPerUnit: 270, roi: 338, paybackMonths: 6, demand: 'high' },
  },
  // Плодовые
  {
    id: '14',
    name: 'Яблоня карликовая',
    latinName: 'Malus domestica',
    type: 'juniper',
    variety: 'Колонновидная',
    health: 'good',
    status: 'growing',
    zone: 'Зона Г',
    plantedDate: '2022-10-15',
    height: 120,
    age: 3,
    notes: 'Начинает плодоносить на 2-3 год.',
    lastWatered: '2024-12-17',
    lastFertilized: '2024-10-30',
    financials: { costPerUnit: 300, sellingPrice: 1000, profitPerUnit: 700, roi: 233, paybackMonths: 10, demand: 'very-high' },
  },
];

export const initialZones: Zone[] = [
  { id: 'z1', name: 'Зона А', capacity: 50, currentCount: 2, description: 'Молодые саженцы' },
  { id: 'z2', name: 'Зона Б', capacity: 40, currentCount: 1, description: 'Крупномерные' },
];

export const initialTasks: Task[] = [
  {
    id: 't1',
    plantId: '1',
    plantName: 'Сосна горная Мугус',
    type: 'pruning',
    dueDate: '2025-03-01',
    completed: false,
    notes: 'Формирующая обрезка',
  },
  {
    id: 't2',
    plantId: '2',
    plantName: 'Ель голубая',
    type: 'fertilizing',
    dueDate: '2025-01-10',
    completed: false,
    notes: 'Комплексная подкормка',
  },
  {
    id: 't3',
    plantId: '3',
    plantName: 'Можжевельник казацкий',
    type: 'watering',
    dueDate: '2025-01-05',
    completed: false,
    notes: 'Полив после пересадки',
  },
];
