import { Plant, Zone, Task, PlantType } from './types';

export const PLANT_TYPE_LABELS: Record<PlantType, string> = {
  pine: 'Сосна',
  spruce: 'Ель',
  fir: 'Пихта',
  juniper: 'Можжевельник',
  cypress: 'Кипарисовик',
  thuja: 'Туя',
  yew: 'Тис',
  larch: 'Лиственница',
};

export const PLANT_TYPE_EMOJIS: Record<PlantType, string> = {
  pine: '🌲',
  spruce: '🎄',
  fir: '🌲',
  juniper: '🌿',
  cypress: '🌳',
  thuja: '🌲',
  yew: '🌿',
  larch: '🍃',
};

export const HEALTH_LABELS = {
  excellent: 'Отличное',
  good: 'Хорошее',
  fair: 'Удовлетворительное',
  poor: 'Плохое',
  critical: 'Критическое',
};

export const HEALTH_COLORS = {
  excellent: '#22c55e',
  good: '#84cc16',
  fair: '#eab308',
  poor: '#f97316',
  critical: '#ef4444',
};

export const STATUS_LABELS = {
  growing: 'Растёт',
  transplanting: 'Пересадка',
  resting: 'Покой',
  sold: 'Продано',
  planned: 'Запланировано',
};

export const STATUS_COLORS = {
  growing: '#22c55e',
  transplanting: '#3b82f6',
  resting: '#a855f7',
  sold: '#6b7280',
  planned: '#f59e0b',
};

export const initialPlants: Plant[] = [
  {
    id: '1',
    name: 'Сосна горная Мугус',
    latinName: 'Pinus mugo Mughus',
    type: 'pine',
    variety: 'Mughus',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2022-03-15',
    height: 85,
    age: 4,
    notes: 'Хорошо перенесла зиму. Нужна формирующая обрезка весной.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-11-01',
  },
  {
    id: '2',
    name: 'Ель голубая',
    latinName: 'Picea pungens',
    type: 'spruce',
    variety: 'Hoopsii',
    health: 'good',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2021-05-20',
    height: 145,
    age: 6,
    notes: 'Активный рост. Требуется подкормка.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-10-15',
  },
  {
    id: '3',
    name: 'Можжевельник казацкий',
    latinName: 'Juniperus sabina',
    type: 'juniper',
    variety: 'Tamariscifolia',
    health: 'good',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2023-04-10',
    height: 35,
    age: 2,
    notes: 'Молодое растение. Хорошо укоренилось.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-11-20',
  },
  {
    id: '4',
    name: 'Туя западная Смарагд',
    latinName: 'Thuja occidentalis Smaragd',
    type: 'thuja',
    variety: 'Smaragd',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона В',
    plantedDate: '2020-09-05',
    height: 180,
    age: 7,
    notes: 'Отличная форма. Готова к продаже.',
    lastWatered: '2024-12-21',
    lastFertilized: '2024-10-01',
  },
  {
    id: '5',
    name: 'Пихта корейская',
    latinName: 'Abies koreana',
    type: 'fir',
    variety: 'Blue Standard',
    health: 'fair',
    status: 'resting',
    zone: 'Зона Б',
    plantedDate: '2022-10-12',
    height: 65,
    age: 5,
    notes: 'Замедлен рост. Нужна диагностика почвы.',
    lastWatered: '2024-12-15',
    lastFertilized: '2024-09-10',
  },
  {
    id: '6',
    name: 'Сосна обыкновенная',
    latinName: 'Pinus sylvestris',
    type: 'pine',
    variety: 'Watereri',
    health: 'good',
    status: 'growing',
    zone: 'Зона Г',
    plantedDate: '2023-03-22',
    height: 50,
    age: 3,
    notes: 'Нормальный рост. Полив по графику.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-11-05',
  },
  {
    id: '7',
    name: 'Ель сербская',
    latinName: 'Picea omorika',
    type: 'spruce',
    variety: 'Pendula',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2021-08-14',
    height: 120,
    age: 5,
    notes: 'Красивая плакучая форма. Гордость коллекции.',
    lastWatered: '2024-12-19',
    lastFertilized: '2024-10-20',
  },
  {
    id: '8',
    name: 'Кипарисовик горохоплодный',
    latinName: 'Chamaecyparis pisifera',
    type: 'cypress',
    variety: 'Filifera Aurea',
    health: 'good',
    status: 'transplanting',
    zone: 'Зона В',
    plantedDate: '2023-06-01',
    height: 40,
    age: 2,
    notes: 'Пересажена на новое место. Наблюдать адаптацию.',
    lastWatered: '2024-12-21',
    lastFertilized: '2024-11-15',
  },
  {
    id: '9',
    name: 'Тис ягодный',
    latinName: 'Taxus baccata',
    type: 'yew',
    variety: 'Fastigiata',
    health: 'good',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2022-07-20',
    height: 95,
    age: 4,
    notes: 'Колонновидная форма. Растёт медленно.',
    lastWatered: '2024-12-17',
    lastFertilized: '2024-10-25',
  },
  {
    id: '10',
    name: 'Лиственница японская',
    latinName: 'Larix kaempferi',
    type: 'larch',
    variety: 'Diana',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона Г',
    plantedDate: '2021-04-18',
    height: 200,
    age: 6,
    notes: 'Спиральные ветви. Очень декоративна.',
    lastWatered: '2024-12-20',
    lastFertilized: '2024-10-10',
  },
  {
    id: '11',
    name: 'Можжевельник чешуйчатый',
    latinName: 'Juniperus squamata',
    type: 'juniper',
    variety: 'Blue Star',
    health: 'excellent',
    status: 'growing',
    zone: 'Зона А',
    plantedDate: '2023-09-05',
    height: 25,
    age: 2,
    notes: 'Компактная голубая звезда. Отличный цвет.',
    lastWatered: '2024-12-18',
    lastFertilized: '2024-11-10',
  },
  {
    id: '12',
    name: 'Сосна чёрная',
    latinName: 'Pinus nigra',
    type: 'pine',
    variety: 'Austriaca',
    health: 'poor',
    status: 'growing',
    zone: 'Зона Б',
    plantedDate: '2020-11-30',
    height: 160,
    age: 8,
    notes: 'Признаки хлороза. Нужна срочная подкормка железом.',
    lastWatered: '2024-12-16',
    lastFertilized: '2024-09-01',
  },
];

export const initialZones: Zone[] = [
  { id: 'z1', name: 'Зона А', capacity: 50, currentCount: 3, description: 'Молодые саженцы и карликовые формы' },
  { id: 'z2', name: 'Зона Б', capacity: 40, currentCount: 4, description: 'Крупномерные хвойные' },
  { id: 'z3', name: 'Зона В', capacity: 30, currentCount: 2, description: 'Декоративные формы и топиарий' },
  { id: 'z4', name: 'Зона Г', capacity: 35, currentCount: 2, description: 'Маточные растения и черенкование' },
];

export const initialTasks: Task[] = [
  { id: 't1', plantId: '12', plantName: 'Сосна чёрная', type: 'fertilizing', dueDate: '2024-12-25', completed: false, notes: 'Подкормка хелатом железа' },
  { id: 't2', plantId: '5', plantName: 'Пихта корейская', type: 'inspection', dueDate: '2024-12-26', completed: false, notes: 'Диагностика состояния почвы' },
  { id: 't3', plantId: '1', plantName: 'Сосна горная Мугус', type: 'pruning', dueDate: '2025-03-01', completed: false, notes: 'Формирующая обрезка' },
  { id: 't4', plantId: '8', plantName: 'Кипарисовик горохоплодный', type: 'inspection', dueDate: '2024-12-28', completed: false, notes: 'Проверка адаптации после пересадки' },
  { id: 't5', plantId: '2', plantName: 'Ель голубая', type: 'fertilizing', dueDate: '2025-01-10', completed: false, notes: 'Комплексная подкормка' },
  { id: 't6', plantId: '4', plantName: 'Туя западная Смарагд', type: 'watering', dueDate: '2024-12-24', completed: true, notes: 'Полив завершён' },
  { id: 't7', plantId: '7', plantName: 'Ель сербская', type: 'watering', dueDate: '2024-12-23', completed: true, notes: 'Плановый полив' },
];
